# https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Header-&-Footer
header-footer:
  enabled: true
  header:
  - ''
  - '&bGodSpunky PvP'
  - ''
  footer:
  - ''
  - '&#55f6ffp&#55edffl&#55e4ffa&#55dbffy&#55d2ff.&#55c9ffg&#55c0ffo&#55b7ffd&#55aeffs&#55a5ffp&#559cffu&#5593ffn&#558affk&#5581ffy&#5578ff.&#556fffi&#5566ffn&#555dff'
  - '&#05af05g&#0ab40ao&#0fb90fd&#14be14s&#19c319p&#1ec81eu&#23cd23n&#28d228k&#2dd72dy&#32dc32.&#37e137s&#3ce63ct&#41eb41o&#46f046r&#4bf54be&#50fa50'
  - '&#555dffd&#5565ffi&#556dffs&#5575ffc&#557dffo&#5585ffr&#558dffd&#5595ff.&#559dffg&#55a5ffg&#55adff/&#55b5ffg&#55bdffo&#55c5ffd&#55cdffs&#55d5ffp&#55ddffu&#55e5ffn&#55edffk&#55f5ffy&#55fdff'
  - ''
  - '&7Online Players: %online%/250'
  per-world:
    world1:
      header:
      - an example of world with custom
      footer:
      - header/footer and prefix/suffix
    world2;world3:
      header:
      - This is a shared header for
      - world2 and world3
  per-server:
    server1:
      header:
      - an example of server with custom header
  disable-condition: '%world%=disabledworld|%server%=disabledserver'
tablist-name-formatting:
  enabled: true
  anti-override: true
  disable-condition: '%world%=disabledworld|%server%=disabledserver'
scoreboard-teams:
  enabled: true
  enable-collision: true
  invisible-nametags: false
  anti-override: true
  sorting-types:
  - GROUPS:god,owner,co-owner,manager,admin,mod,helper,media,godlike,elite,hero,veteran,default
  - PLACEHOLDER_A_TO_Z:%player_name%
  case-sensitive-sorting: true
  can-see-friendly-invisibles: false
  unlimited-nametag-mode:
    enabled: false
    disable-on-boats: true
    dynamic-lines:
    - abovename
    - nametag
    - belowname
    - another
    static-lines:
      myCustomLine: 0.66
    disable-condition: '%world%=disabledworld|%server%=disabledserver'
  disable-condition: '%world%=disabledworld|%server%=disabledserver'
belowname-objective:
  enabled: true
  number: '%health%'
  text: '&c‚ô•'
  disable-condition: '%world%=disabledworld|%server%=disabledserver'
  fancy-display-default: NPC
  fancy-display-players: '&c%health%'
prevent-spectator-effect:
  enabled: false
bossbar:
  enabled: true
  toggle-command: /bossbar
  remember-toggle-choice: false
  hidden-by-default: false
  bars:
    ServerInfo:
      style: PROGRESS
      color: BLUE
      progress: '100'
      text: '&#55f6ff&lP&#55edff&lL&#55e4ff&lA&#55dbff&lY&#55d2ff&l.&#55c9ff&lG&#55c0ff&lO&#55b7ff&lD&#55aeff&lS&#55a5ff&lP&#559cff&lU&#5593ff&lN&#558aff&lK&#5581ff&lY&#5578ff&l.&#556fff&lI&#5566ff&lN&#555dff&l'
scoreboard:
  enabled: true
  toggle-command: /sb
  remember-toggle-choice: false
  hidden-by-default: false
  use-numbers: true
  static-number: 0
  delay-on-join-milliseconds: 0
  respect-other-plugins: true
  scoreboards:
    scoreboard1:
      title: '&#55d5ff&lF&#55abff&lF&#5581ff&lA&#5557ff &7‚îá &#55c7ff&lI&#558fff&lN&#5557ff&l'
      lines:
      - ''
      - '&b%player_name%'
      - '#FF0000| üó° &fKills: #FF0000%statistic_player_kills%'
      - '&6| ‚ò† &fDeaths: &6%statistic_deaths%'
      - '#E8FF00| ‚õè &fKDR: #E8FF00%kdratio_ratio%'
      - '#00FFE8| ‚öî &fStreak: #74FF00%deluxecombat_ranking_streak%'
      - ''
      - '&bServer'
      - '#FFB6C1| ‚òÖ &fOnline: #FFB6C1%online%'
      - '#00FFE8| ‚òÑ &fGlobal: #00FFE8%redisbungee_total%'
      - '&a| &a&l‚ö° &fLatency: %player_colored_ping%ms'
      - ''
      - '&7‚ò£ &7·¥ò ü·¥Ä è.…¢·¥è·¥Ös·¥ò·¥ú…¥·¥ã è.…™…¥'
ping-spoof:
  enabled: true
  value: 69
placeholders:
  date-format: dd.MM.yyyy
  time-format: '[HH:mm:ss / h:mm a]'
  time-offset: 0
placeholder-output-replacements:
  '%essentials_vanished%':
    'yes': '&7| Vanished'
    'no': ''
  '%afk%':
    true: ' &o[AFK]&r'
    false: ''
    '%afk%': ''
conditions:
  nick:
    conditions:
    - '%player%=%player_name%'
    true: '%player_name%'
    false: '%player_name%'
placeholderapi-refresh-intervals:
  default-refresh-interval: 500
  '%server_uptime%': 1000
  '%server_tps_1_colored%': 1000
  '%server_unique_joins%': 5000
  '%player_health%': 200
  '%player_ping%': 1000
  '%vault_prefix%': 1000
  '%rel_factionsuuid_relation_color%': 1000
assign-groups-by-permissions: false
primary-group-finding-list:
- Owner
- Admin
- Mod
- Helper
- default
debug: false
mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  database: tab
  username: user
  password: password
per-world-playerlist:
  enabled: false
  allow-bypass-permission: false
  ignore-effect-in-worlds:
  - ignoredworld
  - build
  shared-playerlist-world-groups:
    lobby:
    - lobby1
    - lobby2
    minigames:
    - paintball
    - bedwars
global-playerlist:
  enabled: false
  display-others-as-spectators: false
  display-vanished-players-as-spectators: true
  isolate-unlisted-servers: false
  spy-servers:
  - spyserver1
  - spyserver2
  server-groups:
    lobbies:
    - lobby1
    - lobby2
    group2:
    - server1
    - server2
use-bukkit-permissions-manager: false
use-online-uuid-in-tablist: true
layout:
  enabled: false
  direction: COLUMNS
  default-skin: mineskin:1753261242
  enable-remaining-players-text: true
  remaining-players-text: '... and %s more'
  empty-slot-ping-value: 1000
  layouts:
    staff:
      condition: permission:tab.staff
      fixed-slots:
      - '1|&3RAM&f:'
      - 2|&b%memory-used%MB / %memory-max%MB
      - '3|&8&m                       '
      - '4|&3TPS&f:'
      - 5|&b%tps%
      groups:
        staff:
          condition: permission:tab.staff
          slots:
          - 24-40
        players:
          slots:
          - 44-80
    default:
      fixed-slots:
      - '1|&3Website&f:'
      - 2|&bmyserver.net
      - '3|&8&m                       '
      - '4|&3Name&f:'
      - 5|&b%player%
      - '7|&3Rank&f:'
      - '8|Rank: %group%'
      - '10|&3World&f:'
      - 11|&b%world%
      - '13|&3Time&f:'
      - 14|&b%time%
      - '21|&3Teamspeak&f:'
      - 22|&bts.myserver.net
      - '23|&8&m                       '
      - '41|&3Store&f:'
      - 42|&bshop.myserver.net
      - '43|&8&m                       '
      groups:
        staff:
          condition: permission:tab.staff
          slots:
          - 24-40
        players:
          slots:
          - 44-80
playerlist-objective:
  enabled: false
  number: ''
  disable-condition: '%world%=disabledworld|%server%=disabledserver'
  fancy-value: '&7Ping: %ping%'
